const B = import.meta.env.BASE_URL;

export const FILAMENT_COLORS = [
  { category: "Neutrals", colors: [
    { name: "White", hex: "#FFFFFF" },
    { name: "Bone White", hex: "#F9F6EE" },
    { name: "Beige", hex: "#D2B48C" },
    { name: "Grey", hex: "#808080" },
    { name: "Black", hex: "#1A1A1A" },
  ]},
  { category: "Reds & Pinks", colors: [
    { name: "Red", hex: "#DC143C" },
    { name: "Pink", hex: "#FF69B4" },
    { name: "Pastel Pink", hex: "#FFD1DC" },
  ]},
  { category: "Oranges & Browns", colors: [
    { name: "Orange", hex: "#FF6600" },
    { name: "Brown", hex: "#8B4513" },
    { name: "Roasted Chestnut", hex: "#986960" },
  ]},
  { category: "Yellows & Golds", colors: [
    { name: "Yellow", hex: "#FFD700" },
    { name: "Silk Gold", hex: "#C5A44E" },
  ]},
  { category: "Greens", colors: [
    { name: "Green", hex: "#228B22" },
    { name: "Olive Green", hex: "#6B8E23" },
  ]},
  { category: "Blues & Purples", colors: [
    { name: "Blue", hex: "#1E90FF" },
    { name: "Cyan", hex: "#00CED1" },
    { name: "Purple", hex: "#8B00FF" },
  ]},
  { category: "Special", colors: [
    { name: "Transparent", hex: "#E0E0E0", transparent: true },
  ]},
];

export const islamicProducts = [
  {
    id: 1,
    name: "Crescent Moon Lamp",
    description:
      "A beautifully crafted 3D-printed crescent moon lamp. Perfect for Ramadan decor or as a year-round reminder of faith.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/crescent-elegant.glb`,
    modelType: "glb",
    placeholderGeometry: "crescentMoon",
    color: "#C9A84C",
    scale: 1.2,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: [
      { name: "Black", rgb: [0, 0, 0], editable: true },
      { name: "Gold", rgb: [200, 170, 76], editable: false },
    ],
    featured: true,
    image: `${B}images/products/islamic/Crescent Moon Lamp.png`,
  },
  {
    id: 3,
    name: "Mosque Miniature",
    description:
      "A detailed miniature mosque model. A stunning centerpiece for your home or office that captures the beauty of Islamic architecture.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/miniature-al-aqsa-mosque.glb`,
    modelType: "glb",
    placeholderGeometry: "mosque",
    color: "#1B5E8A",
    scale: 1.3,
    category: "Decor",
    zoneConfig: "none",
    image: `${B}images/products/islamic/mosque miniture.png`,
  },
  {
    id: 5,
    name: "Prayer Bead Display Stand",
    description:
      "A custom-designed stand to beautifully display your prayer beads (tasbih). Keep your beads organized and within reach.",
    price: "18.99",
    currency: "$",
    modelPath: `${B}models/islamic/prayer-bead-stand.glb`,
    modelType: "glb",
    placeholderGeometry: "beadStand",
    color: "#1A8A7D",
    scale: 1.3,
    category: "Functional",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: "single",
    image: `${B}images/products/islamic/Prayer Bead Display Stand.png`,
  },
  {
    id: 7,
    name: "Ayatul Kursi Frame",
    description:
      "A 3D-printed decorative frame featuring Ayatul Kursi. A meaningful gift for weddings, housewarmings, or any special occasion.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/ayat-al-kursi.glb`,
    modelType: "glb",
    placeholderGeometry: "frame",
    color: "#C9A84C",
    scale: 1.2,
    category: "Gift",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: [
      { name: "Gold", rgb: [100, 55, 15], editable: true },
      { name: "White", rgb: [160, 148, 135], editable: true },
      { name: "Black", rgb: [15, 10, 5], editable: true },
    ],
    image: `${B}images/products/islamic/Ayatul Kursi Frame.png`,
  },
  {
    id: 33,
    name: "Fanoos Ramadan Lamp",
    description:
      "A beautifully detailed 3D-printed fanoos (traditional Ramadan lantern). A stunning centerpiece for your iftar table or mantelpiece during the holy month.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/fanoos.glb`,
    modelType: "glb",
    placeholderGeometry: "icosahedron",
    color: "#C9A84C",
    scale: 1.3,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: "single",
    featured: true,
    image: `${B}images/products/islamic/Fanoos Ramadan Lamp.png`,
  },
  {
    id: 35,
    name: "Bismillah Crescent Desk Piece",
    description:
      "A beautifully crafted crescent moon with Bismillah calligraphy in raised relief, resting on an elegant base. A meaningful accent piece for your desk or prayer space.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/crescent-bismillah.glb`,
    modelType: "glb",
    placeholderGeometry: "crescentMoon",
    color: "#C9A84C",
    scale: 1.2,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: [
      { name: "Gold", rgb: [200, 170, 76], editable: true },
      { name: "Other", rgb: [128, 128, 128], editable: false },
    ],
    image: `${B}images/products/islamic/Bismillah Crescent Desk Piece.png`,
  },
  {
    id: 36,
    name: "Crescent Ramadan Centerpiece",
    description:
      "A decorative crescent moon piece with intricate Ramadan-inspired details on an elegant base. Perfect as a table centerpiece during the holy month or year-round display.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/crescent-ramadan.glb`,
    modelType: "glb",
    placeholderGeometry: "crescentMoon",
    color: "#C9A84C",
    scale: 1.2,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: [
      { name: "Blue", rgb: [0, 50, 200], editable: true },
      { name: "White", rgb: [255, 255, 255], editable: false },
    ],
    image: `${B}images/products/islamic/crescent ramandan center piece.png`,
  },
  {
    id: 38,
    name: "Ramadan Fanoos Lantern",
    description:
      "A traditional Ramadan fanoos lantern with ornate geometric patterns and a warm glow effect. A second unique design to complement your Ramadan decor collection.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/ramadan-fanoos.glb`,
    modelType: "glb",
    placeholderGeometry: "icosahedron",
    color: "#C9A84C",
    scale: 1.3,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: "single",
    image: `${B}images/products/islamic/ramdan fanoos lantern.png`,
  },
  {
    id: 39,
    name: "Crescent Dates Pot",
    description:
      "A crescent moon-shaped pot designed to hold and serve dates. Combines Islamic artistry with everyday function — ideal for iftar gatherings and Ramadan hospitality.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/crescent-dates-pot.glb`,
    modelType: "glb",
    placeholderGeometry: "crescentMoon",
    color: "#C9A84C",
    scale: 1.2,
    category: "Functional",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: [
      { name: "Black", rgb: [0, 0, 0], editable: true },
      { name: "White", rgb: [130, 130, 130], editable: true },
    ],
    image: `${B}images/products/islamic/crescent serving pot.png`,
  },
  {
    id: 40,
    name: "Dates Serving Bowl",
    description:
      "An elegantly crafted serving bowl designed specifically for presenting dates. A beautiful and practical addition to your iftar table or everyday hospitality.",
    price: "19.99",
    currency: "$",
    modelPath: `${B}models/islamic/pot-dates-holder.glb`,
    modelType: "glb",
    placeholderGeometry: "sphere",
    color: "#E2C66D",
    scale: 1.2,
    category: "Functional",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: [
      { name: "Brown", rgb: [45, 25, 5], editable: true },
      { name: "Gold", rgb: [105, 70, 10], editable: true },
      { name: "White", rgb: [103, 96, 89], editable: true },
    ],
    image: `${B}images/products/islamic/dates serving bowl.png`,
  },
  {
    id: 41,
    name: "Ramadan Stand",
    description:
      "A decorative Ramadan-themed display stand, perfect for showcasing dates, sweets, or small lanterns during the holy month.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/ramadan-stand.glb`,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#C9A84C",
    scale: 1.2,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: [
      { name: "Black", rgb: [5, 5, 2], editable: true },
      { name: "Gold", rgb: [100, 55, 3], editable: true },
      { name: "White", rgb: [85, 90, 95], editable: true },
    ],
    image: `${B}images/products/islamic/ramadan stand.png`,
  },
  {
    id: 43,
    name: "Ramadan Crescent with Floats",
    description:
      "A beautifully designed crescent with suspended floating accents. A unique Ramadan decoration that adds a modern touch to traditional Islamic aesthetics.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/ramadan-crescent-with-floats.glb`,
    modelType: "glb",
    placeholderGeometry: "crescentMoon",
    color: "#E2C66D",
    scale: 1.2,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: [
      { name: "Black", rgb: [12, 10, 10], editable: true },
      { name: "Gold", rgb: [140, 90, 25], editable: true },
      { name: "White", rgb: [100, 102, 112], editable: true },
    ],
    image: `${B}images/products/islamic/Ramadan Crescent with Floats.png`,
  },
  {
    id: 44,
    name: "La Ilaha Illa Allah Wall Art",
    description:
      "A 3D-printed wall art piece featuring the Shahada — 'La Ilaha Illa Allah' — in elegant Arabic calligraphy. A meaningful declaration of faith for your home.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/la-ilaha-illa-allah-wall-art.glb`,
    modelType: "glb",
    placeholderGeometry: "calligraphyPanel",
    color: "#C9A84C",
    scale: 1.2,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: [
      { name: "Black", rgb: [0, 0, 0], editable: true },
      { name: "White", rgb: [255, 255, 255], editable: true },
    ],
    image: `${B}images/products/islamic/La Ilaha Illa Allah Wall Art.png`,
  },
  {
    id: 45,
    name: "Alhamdulillah Wall Art",
    description:
      "A beautifully crafted 3D-printed wall piece featuring 'Alhamdulillah' in raised Arabic calligraphy. A daily reminder of gratitude for your living space.",
    price: "24.99",
    currency: "$",
    modelPath: `${B}models/islamic/alhamdulillah-wall-art.glb`,
    modelType: "glb",
    placeholderGeometry: "calligraphyPanel",
    color: "#C9A84C",
    scale: 1.2,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: "single",
    image: `${B}images/products/islamic/Alhamdulillah Wall Art.png`,
  },
  {
    id: 46,
    name: "Hijri Calendar Display",
    description:
      "A 3D-printed Hijri calendar display piece. Keep track of the Islamic calendar dates with this functional and decorative piece for your desk or shelf.",
    price: "22.99",
    currency: "$",
    modelPath: `${B}models/islamic/hijri-calendar.glb`,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#E2C66D",
    scale: 1.2,
    category: "Functional",
    colorOptions: FILAMENT_COLORS,
    zoneConfig: [
      { name: "Black", rgb: [8, 6, 3], editable: true },
      { name: "Gold", rgb: [100, 55, 15], editable: true },
      { name: "White", rgb: [100, 100, 95], editable: true },
    ],
    image: `${B}images/products/islamic/Hijri Calendar Display.png`,
  },
  {
    id: 47,
    name: "Eid Cash Gift Tube",
    description:
      "A tubular Eid gift enclosure where recipients can pull out cash. A creative and fun way to present money gifts during Eid celebrations.",
    price: "12.99",
    currency: "$",
    modelPath: `${B}models/islamic/eid-cash-gift-tube.stl`,
    modelType: "stl",
    placeholderGeometry: "box",
    color: "#C9A84C",
    scale: 1.2,
    modelRotation: [0, Math.PI, 0],
    category: "Gift",
    colorOptions: FILAMENT_COLORS,
    image: `${B}images/products/islamic/Eid Cash Gift Tube.png`,
  },
  {
    id: 48,
    name: "Hasbunallahu Wa Ni'mal Wakeel Wall Art",
    description:
      "A 3D-printed wall art piece featuring the powerful phrase 'Hasbunallahu wa ni'mal wakeel' (Allah is sufficient for us, and He is the best disposer of affairs) in elegant Arabic calligraphy.",
    price: "22.99",
    currency: "$",
    modelPath: `${B}models/islamic/hasbunallah-wall-art.stl`,
    modelType: "stl",
    placeholderGeometry: "calligraphyPanel",
    color: "#C9A84C",
    scale: 1.2,
    modelRotation: [0, Math.PI, 0],
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    image: `${B}images/products/islamic/Hasbunallahu Wa Ni'mal Wakeel Wall Art.png`,
  },
  {
    id: 49,
    name: "Miniature Hanging Lamp",
    description:
      "A delicate miniature lamp designed to hang with strings. A charming decorative piece that adds a warm, traditional touch to any room.",
    price: "16.99",
    currency: "$",
    modelPath: `${B}models/islamic/miniature-hanging-lamp.stl`,
    modelType: "stl",
    placeholderGeometry: "icosahedron",
    color: "#C9A84C",
    scale: 1.3,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
    image: `${B}images/products/islamic/Miniature Hanging Lamp.png`,
  },
  {
    id: 50,
    name: "Quran Prayer Holder",
    description:
      "A practical Quran holder designed for use during prayer. Place it in front of you while praying and fold it flat during sujood for uninterrupted recitation.",
    price: "18.99",
    currency: "$",
    modelPath: `${B}models/islamic/quran-prayer-holder.stl`,
    modelType: "stl",
    placeholderGeometry: "box",
    color: "#E2C66D",
    scale: 1.3,
    category: "Functional",
    colorOptions: FILAMENT_COLORS,
    image: `${B}images/products/islamic/Quran Prayer Holder.png`,
  },
  {
    id: 51,
    name: "Madina Keychain",
    description:
      "A 3D-printed keychain featuring a miniature Madina landmark design. Carry a piece of the holy city wherever you go — a meaningful everyday accessory.",
    price: "6.99",
    currency: "$",
    modelPath: `${B}models/islamic/madina-keychain.glb`,
    modelType: "glb",
    placeholderGeometry: "octahedron",
    color: "#C9A84C",
    scale: 1.2,
    category: "Accessory",
    image: `${B}images/products/islamic/madina keychain.png`,
  },
  {
    id: 52,
    name: "Al-Aqsa Keychain",
    description:
      "A 3D-printed keychain featuring the iconic Al-Aqsa Mosque dome silhouette. A beautiful daily reminder of the holy site — carry it wherever you go.",
    price: "6.99",
    currency: "$",
    modelPath: `${B}models/islamic/al-aqsa-keychain.glb`,
    modelType: "glb",
    placeholderGeometry: "octahedron",
    color: "#C9A84C",
    scale: 1.2,
    category: "Accessory",
    image: `${B}images/products/islamic/al aqsah keychain.png`,
  },
  {
    id: 53,
    name: "Kaaba Keychain",
    description:
      "A 3D-printed keychain featuring a miniature Kaaba design. A beautiful reminder of the holiest site in Islam — perfect as a gift or personal keepsake.",
    price: "6.99",
    currency: "$",
    modelPath: `${B}models/islamic/kaaba-keychain.glb`,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#C9A84C",
    scale: 1.2,
    category: "Accessory",
    image: `${B}images/products/islamic/kaaba keychain.png`,
  },
];

export const nerdyProducts = [
  {
    id: 9,
    name: "Dragon Dice Tower",
    description:
      "A 3D-printed dice tower shaped like a coiled dragon. Roll your D20 in style during tabletop RPG nights.",
    price: "34.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "icosahedron",
    color: "#DC5F00",
    scale: 1.2,
    category: "Gaming",
    colorOptions: FILAMENT_COLORS,
    featured: true,
  },
  {
    id: 10,
    name: "Rocket Ship Phone Stand",
    description:
      "A detailed rocket ship that holds your phone at the perfect angle. One small step for your desk, one giant leap for organization.",
    price: "14.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "cone",
    color: "#CF0A0A",
    scale: 1.3,
    category: "Functional",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 11,
    name: "Mini Millennium Falcon",
    description:
      "A finely detailed starship model for your shelf. A must-have for any sci-fi fan's collection.",
    price: "29.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "dodecahedron",
    color: "#444444",
    scale: 1.2,
    category: "Collectible",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 12,
    name: "Periodic Table Bookends",
    description:
      "Molecular-structure bookends in the shape of caffeine and serotonin molecules. Keep your books happy.",
    price: "24.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#FF8F5E",
    scale: 1.4,
    category: "Functional",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 13,
    name: "Articulated Flexi Dragon",
    description:
      "A fully articulated, print-in-place dragon that flexes and poses. Fidget with it, display it, or gift it.",
    price: "19.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "torusKnot",
    color: "#DC5F00",
    scale: 1.2,
    category: "Toy",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 14,
    name: "Portal Bookend Set",
    description:
      "A pair of bookends that look like interdimensional portals. Your books will look like they're warping through space.",
    price: "27.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "torus",
    color: "#CF0A0A",
    scale: 1.3,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 15,
    name: "Math Dodecahedron Lamp",
    description:
      "A geometric dodecahedron desk lamp with mathematical formulas etched into each face. Illuminating in every sense.",
    price: "32.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "dodecahedron",
    color: "#DC5F00",
    scale: 1.4,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 16,
    name: "DNA Helix Stand",
    description:
      "A twisting double-helix model on a stand. Great for biology enthusiasts or as a conversation-starting desk piece.",
    price: "22.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "torusKnot",
    color: "#333333",
    scale: 1.2,
    category: "Collectible",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 17,
    name: "Infinity Cube",
    description:
      "A classic infinity cube with smooth, satisfying hinges. Flip it endlessly \u2014 perfect for focus and stress relief.",
    price: "9.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#DC5F00",
    scale: 1.2,
    category: "Classic",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 18,
    name: "Gear Spinner",
    description:
      "An interlocking gear fidget spinner with 6 meshing gears. Spin one and watch them all move.",
    price: "12.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "octahedron",
    color: "#CF0A0A",
    scale: 1.3,
    category: "Mechanical",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 19,
    name: "Flexi Worm",
    description:
      "A segmented, articulated worm that wiggles and bends. Oddly satisfying to play with.",
    price: "7.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "torusKnot",
    color: "#DC5F00",
    scale: 1.2,
    category: "Flexi",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 20,
    name: "Clicky Slider",
    description:
      "A sliding mechanism fidget with a deeply satisfying click at each end. Slide, click, repeat.",
    price: "8.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#555555",
    scale: 1.1,
    category: "Clicky",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 21,
    name: "Gyroscope Ball",
    description:
      "A 3D-printed nested gyroscope with multiple spinning rings. Mesmerizing to spin and watch.",
    price: "14.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "sphere",
    color: "#DC5F00",
    scale: 1.3,
    category: "Mechanical",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 22,
    name: "Hex Grid Twist",
    description:
      "A honeycomb-patterned twist fidget. Rotate each hex cell for a satisfying tactile experience.",
    price: "11.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "dodecahedron",
    color: "#CF0A0A",
    scale: 1.2,
    category: "Tactile",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 23,
    name: "Chain Link Fidget",
    description:
      "Interlocking 3D-printed chain links you can twist, pull, and fidget with silently.",
    price: "6.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "torus",
    color: "#777777",
    scale: 1.1,
    category: "Classic",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 24,
    name: "Spring Snake",
    description:
      "A coiled spring-shaped fidget that stretches, compresses, and bounces. Simple, addictive, endlessly fun.",
    price: "8.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "torusKnot",
    color: "#DC5F00",
    scale: 1.2,
    category: "Flexi",
    colorOptions: FILAMENT_COLORS,
  },
];

export const flagsProducts = [
  {
    id: 25,
    name: "Country Flag Desk Stand",
    description:
      "A 3D-printed desk stand with a raised flag of your choice. Represent your heritage proudly on your desk or shelf.",
    price: "14.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#254F22",
    scale: 1.2,
    category: "Display",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 26,
    name: "Palestine Flag Plaque",
    description:
      "A detailed wall plaque featuring the Palestinian flag with raised relief. A meaningful display of solidarity.",
    price: "12.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#F5824A",
    scale: 1.3,
    category: "Heritage",
    colorOptions: FILAMENT_COLORS,
    featured: true,
  },
  {
    id: 27,
    name: "Mini Flag Collection Rack",
    description:
      "A tiered display rack that holds up to 6 mini 3D-printed flags. Perfect for collectors and travelers.",
    price: "19.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#254F22",
    scale: 1.4,
    category: "Display",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 28,
    name: "Heritage Flag Keychain",
    description:
      "A compact, durable keychain featuring your country's flag in vibrant 3D-printed detail. Carry your roots everywhere.",
    price: "6.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "octahedron",
    color: "#D4652F",
    scale: 1.1,
    category: "Accessory",
  },
  {
    id: 29,
    name: "Dual Flag Friendship Stand",
    description:
      "Two flags side by side on a shared stand. Celebrate dual heritage, friendships, or international bonds.",
    price: "17.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#4A7C59",
    scale: 1.3,
    category: "Gift",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 30,
    name: "Flag Bookend Set",
    description:
      "A pair of bookends shaped like waving flags. Keep your books organized with a patriotic touch.",
    price: "22.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#F5824A",
    scale: 1.4,
    category: "Functional",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 31,
    name: "Raised Relief Map Flag",
    description:
      "A 3D-printed topographic country map with the national flag colors. Geography meets art in this unique display piece.",
    price: "29.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "dodecahedron",
    color: "#254F22",
    scale: 1.2,
    category: "Decor",
    colorOptions: FILAMENT_COLORS,
  },
  {
    id: 32,
    name: "Custom Text Flag Stand",
    description:
      "A flag stand with a customizable text plate. Add your name, a date, or a message beneath your chosen flag.",
    price: "16.99",
    currency: "$",
    modelPath: null,
    modelType: "glb",
    placeholderGeometry: "box",
    color: "#F9A06C",
    scale: 1.2,
    category: "Custom",
    colorOptions: FILAMENT_COLORS,
  },
];

export const productsByCategory = {
  islamic: islamicProducts,
  nerdy: nerdyProducts,
  flags: flagsProducts,
};

// Backward-compatible default export
export const products = islamicProducts;
