const B = import.meta.env.BASE_URL;

export const THEMES = {
  islamic: {
    id: "islamic",
    label: "Islamic Collection",
    colors: {
      "--color-primary": "#102E50",
      "--color-primary-dark": "#0B2240",
      "--color-primary-light": "#1A4068",
      "--color-accent": "#C9A84C",
      "--color-accent-light": "#E2C66D",
      "--color-accent-dark": "#9B7E2E",
      "--color-tile": "#2574A8",
      "--color-tile-light": "#3A92C8",
      "--color-tile-dark": "#1A5580",
      "--color-turquoise": "#3BB8D0",
      "--color-turquoise-light": "#5CD4E8",
      "--color-bg": "#4A90C8",
      "--color-bg-card": "#FFFFFF",
      "--color-bg-dark": "#0E2640",
      "--color-text": "#1E293B",
      "--color-text-muted": "#334155",
      "--color-text-bright": "#0F172A",
      "--color-text-on-dark": "#CBD5E1",
      "--color-whatsapp": "#25d366",
      "--color-dome": "#C9A84C",
      "--color-dome-light": "#E2C66D",
    },
    scene: {
      canvasBackground: "#4A90C8",
      sparklesColor: "#c9a84c",
      floatingModelColors: [
        "#C9A84C", "#E2C66D", "#2574A8", "#3BB8D0",
        "#1A5580", "#5CD4E8", "#28B5A4", "#9B7E2E",
      ],
      glbModels: [
        `${B}models/islamic/fanoos.glb`,
        `${B}models/islamic/crescent-elegant.glb`,
        `${B}models/islamic/crescent-bismillah.glb`,
        `${B}models/islamic/crescent-ramadan.glb`,
        `${B}models/islamic/miniature-al-aqsa-mosque.glb`,
        `${B}models/islamic/ramadan-fanoos.glb`,
        `${B}models/islamic/crescent-dates-pot.glb`,
        `${B}models/islamic/pot-dates-holder.glb`,
        `${B}models/islamic/ramadan-stand.glb`,
        `${B}models/islamic/ramadan-crescent-with-floats.glb`,
        `${B}models/islamic/la-ilaha-illa-allah-wall-art.glb`,
        `${B}models/islamic/alhamdulillah-wall-art.glb`,
        `${B}models/islamic/hijri-calendar.glb`,
        `${B}models/islamic/ayat-al-kursi.glb`,
        `${B}models/islamic/prayer-bead-stand.glb`,
        `${B}models/islamic/eid-cash-gift-tube.stl`,
        `${B}models/islamic/hasbunallah-wall-art.stl`,
        `${B}models/islamic/miniature-hanging-lamp.stl`,
        `${B}models/islamic/quran-prayer-holder.stl`,
        `${B}models/islamic/madina-keychain.glb`,
        `${B}models/islamic/al-aqsa-keychain.glb`,
        `${B}models/islamic/kaaba-keychain.glb`,
      ],
      lightColors: {
        warm: "#FFE4A0",
        cool: "#4A90D9",
        accent: "#C9A84C",
        ambient: "#B0C4DE",
      },
    },
    frame: {
      gold: "#C9A84C",
      darkA: "#0E2640",
      darkB: "#102E50",
    },
    cursorAccent: "201,168,76",
    bgPatternClass: "islamic-bg",
    showSeasonalBanner: true,
  },

  nerdy: {
    id: "nerdy",
    label: "Nerdy Collection",
    colors: {
      "--color-primary": "#1a0a2e",
      "--color-primary-dark": "#0d0518",
      "--color-primary-light": "#2d1450",
      "--color-accent": "#00FF88",
      "--color-accent-light": "#66FFB3",
      "--color-accent-dark": "#00CC6A",
      "--color-tile": "#2d1450",
      "--color-tile-light": "#4a2080",
      "--color-tile-dark": "#150830",
      "--color-turquoise": "#00FF88",
      "--color-turquoise-light": "#66FFB3",
      "--color-bg": "#120828",
      "--color-bg-card": "#0d0518",
      "--color-bg-dark": "#050208",
      "--color-text": "#E8E0F0",
      "--color-text-muted": "#A898C0",
      "--color-text-bright": "#FFFFFF",
      "--color-text-on-dark": "#D0C4E0",
      "--color-whatsapp": "#25d366",
      "--color-dome": "#00FF88",
      "--color-dome-light": "#66FFB3",
    },
    scene: {
      canvasBackground: "#080412",
      sparklesColor: "#8c2ceb",
      floatingModelColors: [
        "#8c2ceb", "#b87df0", "#00FF88", "#4e0f89",
        "#6A2DB8", "#66FFB3", "#241434", "#00CC6A",
      ],
      glbModels: [
        // Add nerdy GLB models here as they are created (e.g., `${B}models/nerdy/dice-tower.glb")
      ],
      lightColors: {
        warm: "#D4A8FF",
        cool: "#4e0f89",
        accent: "#00FF88",
        ambient: "#B8A0D0",
      },
    },
    frame: {
      gold: "#00FF88",
      darkA: "#050208",
      darkB: "#0d0518",
    },
    cursorAccent: "0,255,136",
    bgPatternClass: "nerdy-bg",
    showSeasonalBanner: false,
  },

  flags: {
    id: "flags",
    label: "Flags Collection",
    colors: {
      "--color-primary": "#3B4856",
      "--color-primary-dark": "#1F2937",
      "--color-primary-light": "#4B5C6B",
      "--color-accent": "#9A6040",
      "--color-accent-light": "#D4A07A",
      "--color-accent-dark": "#7D4E33",
      "--color-tile": "#4B5C6B",
      "--color-tile-light": "#6B7D8D",
      "--color-tile-dark": "#3B4856",
      "--color-turquoise": "#7EB8C9",
      "--color-turquoise-light": "#A5D1DD",
      "--color-bg": "#5C6E7E",
      "--color-bg-card": "#E8E2DC",
      "--color-bg-dark": "#1A2330",
      "--color-text": "#1A1E22",
      "--color-text-muted": "#3A434C",
      "--color-text-bright": "#0F1215",
      "--color-text-on-dark": "#D0D8E0",
      "--color-whatsapp": "#25d366",
      "--color-dome": "#9A6040",
      "--color-dome-light": "#D4A07A",
    },
    scene: {
      canvasBackground: "#5C6E7E",
      sparklesColor: "#9A6040",
      floatingModelColors: [
        "#9A6040", "#D4A07A", "#7EB8C9", "#4B5C6B",
        "#A5D1DD", "#3B4856", "#beb8b1", "#6B7D8D",
      ],
      glbModels: [
        // Add flags GLB models here as they are created (e.g., `${B}models/flags/flag-stand.glb")
      ],
      lightColors: {
        warm: "#D4A07A",
        cool: "#4B5C6B",
        accent: "#9A6040",
        ambient: "#beb8b1",
      },
    },
    frame: {
      gold: "#9A6040",
      darkA: "#1A2330",
      darkB: "#3B4856",
    },
    cursorAccent: "154,96,64",
    bgPatternClass: "flags-bg",
    showSeasonalBanner: false,
  },
};

export const THEME_ORDER = ["islamic", "nerdy", "flags"];
export const DEFAULT_THEME = "islamic";
